### ISSUE TITLE
Convert Docker Compose Setup to Kubernetes Helm Chart

### ISSUE THREAD

**Issue by jerry-enebeli** [blnkfinance/blnk#32]
#### Description:

We need to convert our current Docker Compose setup into a Kubernetes Helm chart. This will help us deploy our services more efficiently on a Kubernetes cluster. Below is the existing `docker-compose.yml` configuration and the requirements for the Helm chart.

#### Current Docker Compose Configuration:

```yaml
version: '3.8'

services:
  server:
    image: jerryenebeli/blnk:v0.6.2
    restart: on-failure
    ports:
      - "5001:5001"
      - "80:80"
      - "443:443"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./blnk.json:/blnk.json

  worker:
    image: jerryenebeli/blnk:v0.6.2
    restart: on-failure
    entrypoint: [ "./blnk", "workers"]
    depends_on:
      - redis
      - postgres
    volumes:
      - ./blnk.json:/blnk.json

  migration:
    image: jerryenebeli/blnk:v0.6.2
    entrypoint: [ "./blnk", "migrate","up" ]
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./blnk.json:/blnk.json

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blnk
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  typesense:
    image: typesense/typesense:0.23.1
    command: ["--data-dir", "/data", "--api-key=blnk-api-key", "--listen-port", "8108"]
    volumes:
      - typesense_data:/data
    ports:
      - "8108:8108"

volumes:
  pg_data:
  typesense_data:
```

#### Requirements for the Helm Chart:

1. **Chart Structure:**
   - Create a new Helm chart with the necessary folder structure (`templates`, `charts`, `values.yaml`, `Chart.yaml`, etc.).

2. **Services:**
   - **Server:**
     - Deploy as a `Deployment` with appropriate `Service` definition.
     - Expose ports 5001, 80, and 443.
     - Mount the `blnk.json` configuration file.
   - **Worker:**
     - Deploy as a `Deployment` with appropriate `Service` definition.
     - Use the custom entrypoint `./blnk workers`.
     - Mount the `blnk.json` configuration file.
   - **Migration:**
     - Deploy as a `Job` to run database migrations.
     - Use the custom entrypoint `./blnk migrate up`.
     - Mount the `blnk.json` configuration file.
   - **Redis:**
     - Deploy as a `Deployment` with appropriate `Service` definition.
     - Expose port 6379.
   - **Postgres:**
     - Deploy as a `StatefulSet` with appropriate `Service` definition.
     - Expose port 5432.
     - Use environment variables for `POSTGRES_USER`, `POSTGRES_PASSWORD`, and `POSTGRES_DB`.
     - Include a health check using `pg_isready`.
     - Persist data using a `PersistentVolumeClaim`.
   - **Typesense:**
     - Deploy as a `Deployment` with appropriate `Service` definition.
     - Expose port 8108.
     - Use command arguments for `--data-dir`, `--api-key`, and `--listen-port`.
     - Persist data using a `PersistentVolumeClaim`.

3. **Volumes:**
   - Define PersistentVolumeClaims for `pg_data` and `typesense_data`.

4. **Configuration:**
   - Create `values.yaml` to allow customization of image tags, replicas, resource limits, and environment variables.

5. **Templates:**
   - Create template files for `Deployment`, `Service`, `StatefulSet`, `Job`, and `PersistentVolumeClaim`.

6. **Documentation:**
   - Provide a detailed README with instructions on how to install and configure the Helm chart.
